## Exam Review - Fall 2016 Final Exam
---
---

In [1]:
import sys
sys.path.insert(2, r'../Modules')
import numpy as np
import linear_algebra as lin
import matrix as mtx
import conversions as conv
import molecular_weights as mw

---
---
##### 1. Find the volume of a parallelpiped with edges given by the following vectors:
**ī** + 2**j̄** + 4**k̄**  
**ī** + **k̄**  
3**j̄** - **k̄**

---

In [2]:
vec1 = np.array([1,2,4])
vec2 = np.array([1,0,1])
vec3 = np.array([0,3,-1])
Matrix = np.array([vec1,vec2,vec3])

print("The volume of the parallepiped in question is {volume}".format(volume=mtx.determinant(Matrix)))
print("The volume of the parallepiped in question is {volume}".format(volume=lin.dot_product(lin.cross_product(vec1,vec2),vec3)))

The volume of the parallepiped in question is 11.0
The volume of the parallepiped in question is 11.0


---
---
##### 2. Which point is in the plane containing the origin and parallel to  
2*x* + *y* - *z* = 4

---

If we are dealing with parallel planes, then *a* can be anything, as the tangent vector and slope won't change. So "plugging" the origin into the equation and solving for *a* gives us the last piece of the parallel plane in question

In [3]:
options2 = {
    '𝐚':np.array([1,3,1]),
    '𝐛':np.array([1,1,1]),
    '𝐜':np.array([2,0,4]),
    '𝐝':np.array([0,1,2]),
    '𝐞':np.array([5,1,6]),
}

coef = np.array([2,1,-1])
a = lambda var: lin.dot_product(var, coef)

origin = np.zeros(3)
print("2𝑥 + 𝑦 - 𝑧 = {a}".format(a=a(origin)))

2𝑥 + 𝑦 - 𝑧 = 0.0


Then, "plugging" the various points into the equation we can see which of them have the same *a*, and will thus be on the same plane.

In [4]:
for key in options2:
    print("{key}: {value} · {coef} = {a_option} {EQ} {a_origin} {arrow}".format(
        key=key, value=options2[key], coef=coef, a_option = a(options2[key]), a_origin = a(origin),
        EQ = "==" if a(options2[key]) == a(origin) else "!=",
        arrow = "<-----" if a(options2[key]) == a(origin) else ""
    ))

𝐚: [1 3 1] · [ 2  1 -1] = 4 != 0.0 
𝐛: [1 1 1] · [ 2  1 -1] = 2 != 0.0 
𝐜: [2 0 4] · [ 2  1 -1] = 0 == 0.0 <-----
𝐝: [0 1 2] · [ 2  1 -1] = -1 != 0.0 
𝐞: [5 1 6] · [ 2  1 -1] = 5 != 0.0 


---
---
##### 3. Which vector is perpendicular to the following line?  
**r̄**(*t*) = (**ī** + 3 **j̄** + **k̄**) + *t*(2**ī** + **j̄** + 2**k̄**)  

---

In [5]:
options3 = {
    '𝐚':np.array([2,-1,1]),
    '𝐛':np.array([1,-2,1]),
    '𝐜':np.array([1,-2,4]),
    '𝐝':np.array([1,2,-2]),
    '𝐞':np.array([-2,3,1]),
}
r_0 = np.array([1,3,1])
r_slope = np.array([2,1,2])
r = lambda t: r_0 + t * r_slope
print("r̄(𝑡) = {inter} + 𝑡{slope}".format(inter = r_0, slope = r_slope))

r̄(𝑡) = [1 3 1] + 𝑡[2 1 2]


The dot product of two perpendicular vectors is equal to 0.

In [6]:
for key in options3:
    dot = lin.dot_product(r_slope,options3[key])
    print("{key}: {value} · {slope} = {dot} {EQ} 0 {arrow}".format(
        key=key, value=options3[key], slope=r_slope, dot=dot,
        EQ = "==" if dot == 0 else "!=",
        arrow = "<-----" if dot == 0 else ""
    ))

𝐚: [ 2 -1  1] · [2 1 2] = 5 != 0 
𝐛: [ 1 -2  1] · [2 1 2] = 2 != 0 
𝐜: [ 1 -2  4] · [2 1 2] = 8 != 0 
𝐝: [ 1  2 -2] · [2 1 2] = 0 == 0 <-----
𝐞: [-2  3  1] · [2 1 2] = 1 != 0 


---
---
##### 4. What is the distance between the line **r̄**(𝑡) = (1,0,1)+𝑡(1,2,2) and the point P(3,3,3)?

---

In [7]:
options4 = {
    '𝐚':1,
    '𝐛':4/5,
    '𝐜':3/4,
    '𝐝':2,
    '𝐞':np.sqrt(2),
}

r_0 = np.array([1,0,1])
r_slope = np.array([1,2,2])
r = lambda t: r_0 + t*r_slope
print("r̄(𝑡) = {inter} + 𝑡{slope}".format(inter = r_0,slope = r_slope))

P = np.array([3,3,3])
print("P = {point}".format(point=P)) 

r̄(𝑡) = [1 0 1] + 𝑡[1 2 2]
P = [3 3 3]


Setting Q = **r̄(0)** and substracting it from P we find **Q̄P̄**. Then taking the norm of the cross product of **Q̄P̄** and the slope of **r̄** and dividing it by ||**r̄**|| we find the length of the component of **Q̄P̄** that is perpendicular to **r̄**, and thus the shortest distance between P and **r̄**.

In [8]:
dist = lin.norm(lin.cross_product(P-r(0),r_slope))/lin.norm(r_slope)

print("The distance between P and r̄, calculated using the cross product formula is {dist}".format(
    dist = dist))
print("Alternatively, using the point_line_distance(P,r̄) function we get {dist}".format(
    dist = lin.point_line_distance(P,r)))

print("||(P-R(0)) 𝗑 R_slope|| / ||R_slope||  =  ||{PR0} 𝗑 {slope}|| / ||{slope}||  =  ||{cross}|| / {slope_norm}  =  {dist}".format(
        PR0=P-r(0), slope=r_slope, dist = dist, cross=lin.cross_product(P-r(0),r_slope), slope_norm = lin.norm(r_slope)))

The distance between P and r̄, calculated using the cross product formula is 1.0
Alternatively, using the point_line_distance(P,r̄) function we get 1.0
||(P-R(0)) 𝗑 R_slope|| / ||R_slope||  =  ||[2 3 2] 𝗑 [1 2 2]|| / ||[1 2 2]||  =  ||[ 2. -2.  1.]|| / 3.0  =  1.0


In [9]:
for key in options4:
    print("{key}: {value:.2f} {EQ} {dist} {arrow}".format(
        key=key, value=options4[key], dist = dist,
        EQ = "==" if options4[key] == dist else "!=",
        arrow = "<-----" if options4[key] == dist else ""
    ))

𝐚: 1.00 == 1.0 <-----
𝐛: 0.80 != 1.0 
𝐜: 0.75 != 1.0 
𝐝: 2.00 != 1.0 
𝐞: 1.41 != 1.0 


---
---
##### 5. For which values of k does the system with the given augmented matrix have a unique solution?
---

In [10]:
A = lambda k: np.array([[1, -1],[k, 1]])
b = np.array([[2],[-2]])
A_inv = lambda k: mtx.inverse(A(k))

In [11]:
options5 = {
    '𝐚':0,
    '𝐛':-1,
    '𝐜':1,
    '𝐝':2,
    '𝐞':3,
}

In [12]:
for key in options5:
    if (A_inv(options5[key]) is None):
        print("{key}: 𝑨({value:.2f})_inv == None".format(key=key, value=options5[key]))
    else:
        print("{key}: x̄ =\n{X}".format(key=key, X=mtx.multiply(A_inv(options5[key])[0],b)))

𝐚: x̄ =
[[ 0.]
 [-2.]]
𝐛: 𝑨(-1.00)_inv == None
𝐜: x̄ =
[[ 0.]
 [-2.]]
𝐝: x̄ =
[[ 1.11022302e-16]
 [-2.00000000e+00]]
𝐞: x̄ =
[[ 0.]
 [-2.]]
